version: "3"
services:
  db:
    image: mongo:5.0.9
    container_name: db

    ports:
      - "4000:27017"
    restart: always
  # Add the azure-storage service with similar configurations to the video-streaming service
  azure-storage:
    image: azure-storage
    build:
      context: ./azure-storage/
      dockerfile: dev.Dockerfile

    container_name: video-storage

    volumes:
      # The syntax is the usual host:container
      - ./tmp/azure-storage/npm-cache:/root/.npm:z
      - ./azure-storage/src:/usr/src/app/src:z

    ports:
      - "4001:80"
    environment:
      - PORT=80
      - STORAGE_ACCOUNT_NAME=${STORAGE_ACCOUNT_NAME}
      - STORAGE_ACCESS_KEY=${STORAGE_ACCESS_KEY}

  video-streaming:
    image: video-streaming # image name
    build: # build from dev.Dockerfile
      context: ./video-streaming # path to dev.Dockerfile
      dockerfile: dev.Dockerfile # dev.Dockerfile name

    container_name: video-streaming # container name

    volumes:
      # The syntax is the usual host:container
      - ./tmp/video-streaming/npm-cache:/root/.npm:z
      - ./video-streaming/src:/usr/src/app/src:z

    ports:
      - "4002:80" # host:container

    environment:
      - PORT=80 # port to run the server on
      - DBHOST=mongodb://db:27017
      - DBNAME=video-streaming
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
      - RABBIT=amqp://guest:guest@rabbitmq:5672

    depends_on:
      - rabbitmq

    restart: "no"

  #Define the history microservice with a Docker volume for the code in the src folder for a live reload during development
  history:
    image: history # image name
    build: # build from dev.Dockerfile
      context: ./history # path to dev.Dockerfile
      dockerfile: dev.Dockerfile # dev.Dockerfile name

    container_name: history # container name

    ports:
      - "4003:80" # host:container

    environment:
      - PORT=80 # port to run the server on
      - NODE_ENV=development
      - DBHOST=mongodb://db:27017
      - DBNAME=history
      - RABBIT=amqp://guest:guest@rabbitmq:5672
    volumes:
      # The syntax is the usual host:container
      # NOTE: the z flag simply indicates Docker that the volume is to be shared (potentially among multiple containers).
      - ./tmp/history/npm-cache:/root/.npm:z
      - ./history/src:/usr/src/app/src:z
    depends_on:
      - rabbitmq
      - db
    restart: "no"

  # Define a rabbitmq service with restart set to always
  rabbitmq:
    image: rabbitmq:3.9.21-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
      - "15672"
    restart: always
