version: "3"
services:
  db:
    image: mongo:5.0.9
    container_name: db

    ports:
      - "4000:27017"
    restart: always
  # Add the azure-storage service with similar configurations to the video-streaming service
  azure-storage:
    image: azure-storage
    build:
      context: ./azure-storage/
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - STORAGE_ACCOUNT_NAME=${STORAGE_ACCOUNT_NAME}
      - STORAGE_ACCESS_KEY=${STORAGE_ACCESS_KEY}

  video-streaming:
    image: video-streaming # image name
    build: # build from Dockerfile
      context: ./video-streaming # path to Dockerfile
      dockerfile: Dockerfile # Dockerfile name

    container_name: video-streaming # container name

    ports:
      - "4002:80" # host:container

    environment:
      - PORT=80 # port to run the server on
      - DBHOST=mongodb://db:27017
      - DBNAME=video-streaming
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80

    restart: "no"
