# Create a new deployment named my-deployment using existing video-streaming image and expose it as a service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-streaming
  namespace: default
  labels:
    app: video-streaming
spec:
  selector:
    matchLabels:
      app: video-streaming
  replicas: 1
  template:
    metadata:
      labels:
        app: video-streaming
    spec:
      containers:
        - name: video-streaming
          image: video-streaming:1
          imagePullPolicy: Never
          env:
            - name: PORT
              value: "4000"
---
apiVersion: v1
kind: Service
metadata:
  name: video-streaming
  namespace: default
spec:
  selector:
    app: video-streaming
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
      nodePort: 30000
---
